version: '3.8'
services:
  mongo:
    image: mongo
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    links:
     - mongo
    depends_on:
     - mongo
