filebeat.modules:
  - module: elasticsearch
    logs:
      enabled: true
    metrics:
      enabled: true
    hosts: ["localhost:9200"]
  
  - module: kibana
    metricsets: ["status"]
    enabled: true
    hosts: ["localhost:5601"]

  - module: rabbitmq
    metricsets: ["node"]
    enabled: true
    hosts: ["rabbitmq:15672"]

  - module: jaeger
    metricsets: ["collector"]
    enabled: true
    hosts: ["jaeger:14250"]

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

logging.level: debug
logging.selectors: ["*"]
