metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: prometheus
    period: 10s
    hosts: ["jaeger:14269"] # Update this if your Prometheus metrics are served by a different service
    metrics_path: "/metrics"
  
  - module: system
    metricsets:
      - process
    processes: ['.*']
    period: 10s
  
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

output.elasticsearch:
  hosts: ["localhost:9200"] # Monitoring cluster

setup.kibana:
  host: "kibana:5601"
